# Generated by Django 5.0.6 on 2025-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelcalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oSec01Field01', models.CharField(default='', max_length=100)),
                ('oSec01Field02', models.CharField(default='', max_length=100)),
                ('oSec01Field03', models.CharField(default='', max_length=100)),
                ('oSec01Field04', models.CharField(default='', max_length=100)),
                ('oSec01Field05', models.CharField(default='', max_length=100)),
                ('oSec01Field06', models.CharField(default='', max_length=100)),
                ('oSec01Field07', models.CharField(default='', max_length=100)),
                ('oSec01Field08', models.CharField(default='', max_length=100)),
                ('oSec01Field09', models.CharField(default='', max_length=100)),
                ('oSec01Field10', models.CharField(default='', max_length=100)),
                ('oSec01Field11', models.CharField(default='', max_length=100)),
                ('oSec01Field12', models.CharField(default='', max_length=100)),
                ('oSec01Field13', models.CharField(default='', max_length=100)),
                ('oSec01Field14', models.CharField(default='', max_length=100)),
                ('oSec01Field15', models.CharField(default='', max_length=100)),
                ('oSec01Field16', models.CharField(default='', max_length=100)),
                ('oSec01Field17', models.CharField(default='', max_length=100)),
                ('oSec01Field18', models.CharField(default='', max_length=100)),
                ('oSec01Field19', models.CharField(default='', max_length=100)),
                ('oSec01Field20', models.CharField(default='', max_length=100)),
                ('oSec02Field01', models.CharField(default='', max_length=100)),
                ('oSec02Field02', models.CharField(default='', max_length=100)),
                ('oSec02Field03', models.CharField(default='', max_length=100)),
                ('oSec02Field04', models.CharField(default='', max_length=100)),
                ('oSec02Field05', models.CharField(default='', max_length=100)),
                ('oSec02Field06', models.CharField(default='', max_length=100)),
                ('oSec02Field07', models.CharField(default='', max_length=100)),
                ('oSec02Field08', models.CharField(default='', max_length=100)),
                ('oSec02Field09', models.CharField(default='', max_length=100)),
                ('oSec02Field10', models.CharField(default='', max_length=100)),
                ('oSec02Field11', models.CharField(default='', max_length=100)),
                ('oSec02Field12', models.CharField(default='', max_length=100)),
                ('oSec02Field13', models.CharField(default='', max_length=100)),
                ('oSec02Field14', models.CharField(default='', max_length=100)),
                ('oSec02Field15', models.CharField(default='', max_length=100)),
                ('oSec02Field16', models.CharField(default='', max_length=100)),
                ('oSec02Field17', models.CharField(default='', max_length=100)),
                ('oSec02Field18', models.CharField(default='', max_length=100)),
                ('oSec02Field19', models.CharField(default='', max_length=100)),
                ('oSec02Field20', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
