# Generated by Django 5.0.6 on 2025-01-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0003_modelcalc_osec00field01_modelcalc_osec00field02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec01Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec01Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec02Field01',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec02Field02',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec02Field03',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
