# Generated by Django 5.0.6 on 2025-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0004_alter_modelcalc_osec01field06_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('initial_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
