# Generated by Django 5.0.6 on 2025-02-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0005_formfieldconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldconfig',
            name='visibility',
            field=models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], default='Show', max_length=10),
        ),
        migrations.AlterField(
            model_name='formfieldconfig',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
