# Generated by Django 5.0.6 on 2025-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0006_formfieldconfig_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec03Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec04Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec05Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec06Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec07Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec08Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec09Field20',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field03',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field04',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field05',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field06',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field07',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field08',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field09',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field16',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field17',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field18',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field19',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec10Field20',
            field=models.CharField(default='', max_length=100),
        ),
    ]
