# Generated by Django 5.0.6 on 2025-03-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0008_project_remove_modelcalc_osec03field01_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCompanies', models.CharField(max_length=255)),
            ],
        ),
    ]
