# Generated by Django 5.0.9 on 2025-04-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0014_alogentry'),
        ('aAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='aAppProject.app_project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
