# Generated by Django 5.0.9 on 2025-04-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0015_alter_machine_project_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
