# Generated by Django 5.0.9 on 2025-04-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0016_delete_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelcalc',
        ),
    ]
