# Generated by Django 5.0.6 on 2025-01-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAdmin', '0003_autho_remove_role_pages_remove_userprofile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAutho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aAdmin.autho')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aAdmin.role')),
            ],
        ),
    ]
