# Generated by Django 5.0.9 on 2025-04-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aAdmin', '0004_roleautho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autho',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.DeleteModel(
            name='RoleAutho',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
