# Generated by Django 4.2 on 2025-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAdmin', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyValue', models.CharField(max_length=255)),
                ('CalculationField', models.CharField(max_length=255)),
                ('SubmittalField', models.CharField(max_length=255)),
            ],
        ),
    ]
