# Generated by Django 4.2 on 2025-06-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0017_delete_modelcalc'),
        ('aAdmin', '0007_datatransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatransfer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aAppMechanical.companies'),
        ),
    ]
