# Generated by Django 5.0.9 on 2025-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyValue', models.CharField(max_length=255)),
                ('nameForm', models.CharField(max_length=255)),
                ('nameDB', models.CharField(max_length=255)),
                ('nameMachine', models.CharField(max_length=255)),
            ],
        ),
    ]
