# Generated by Django 5.0.9 on 2025-05-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0004_machine_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachine',
            name='nameDXF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addmachine',
            name='nameFullDrawing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
