# Generated by Django 4.2 on 2025-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0005_addmachine_namedxf_addmachine_namefulldrawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachine',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
