# Generated by Django 4.2 on 2025-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0006_addmachine_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmachine',
            name='order',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
