# Generated by Django 4.2 on 2025-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0008_alter_addmachine_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmachine',
            name='primarynameDXF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addmachine',
            name='primarynameFullDrawing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
