# Generated by Django 4.2 on 2025-05-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0009_addmachine_primarynamedxf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXF_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetkey', models.CharField(max_length=255)),
                ('fieldname', models.CharField(max_length=255)),
                ('fieldvalue', models.CharField(max_length=255)),
            ],
        ),
    ]
