# Generated by Django 4.2 on 2025-06-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0017_delete_modelcalc'),
        ('aAppSubmittal', '0010_dxf_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxf_data',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aAppMechanical.companies'),
        ),
    ]
