# Generated by Django 4.2 on 2025-06-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0011_dxf_data_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxf_data',
            name='horv',
            field=models.CharField(blank=True, choices=[('H', 'H'), ('V', 'V')], max_length=10, null=True),
        ),
    ]
