# Generated by Django 4.2 on 2025-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0012_dxf_data_horv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxf_data',
            name='horv',
            field=models.CharField(choices=[('Select H or V ......', 'Select H or V ......'), ('H', 'H'), ('V', 'V')], default='Select H or V ......', max_length=30),
        ),
    ]
