# Generated by Django 4.2 on 2025-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppSubmittal', '0013_alter_dxf_data_horv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxf_data',
            name='horv',
            field=models.CharField(choices=[('H', 'H'), ('V', 'V')], default='H', max_length=10),
        ),
    ]
