# Generated by Django 5.0.6 on 2025-01-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec01Field06',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelcalc',
            name='oSec01Field07',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
