# Generated by Django 5.0.6 on 2025-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppMechanical', '0002_alter_modelcalc_osec01field06_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcalc',
            name='oSec00Field01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec00Field02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec00Field03',
            field=models.CharField(default='', max_length=100),
        ),
    ]
