# Generated by Django 5.0.6 on 2025-06-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aCost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=50)),
                ('category_id', models.IntegerField()),
                ('row_number', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aCost.categoryitem')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aCost.itemsize')),
            ],
            options={
                'unique_together': {('project_type', 'category_id', 'row_number')},
            },
        ),
    ]
