# Generated by Django 5.0.9 on 2025-04-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0001_initial'),
        ('aAppMechanical', '0017_delete_modelcalc'),
        ('aAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcalc',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aAppMechanical.companies'),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinescalc', to='aAppProject.app_project'),
        ),
    ]
