# Generated by Django 5.0.9 on 2025-04-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0002_modelcalc_company_modelcalc_project'),
        ('aAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcalc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aAppProject.app_project'),
        ),
    ]
