# Generated by Django 5.0.9 on 2025-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0004_alter_modelcalc_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field21',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field23',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field24',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field25',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field26',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field27',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field28',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field29',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec01Field30',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field21',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field22',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field23',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field24',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field25',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field26',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field27',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field28',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field29',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelcalc',
            name='oSec02Field30',
            field=models.CharField(default='', max_length=100),
        ),
    ]
