# Generated by Django 5.0.9 on 2025-04-29 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0006_modelcalc_log'),
        ('aAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcalc',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calcmachines', to='aAppProject.app_project'),
        ),
        migrations.AlterField(
            model_name='modelcalc_log',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calcmachines_log', to='aAppProject.app_project'),
        ),
    ]
