# Generated by Django 5.0.9 on 2025-05-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0007_alter_modelcalc_project_alter_modelcalc_log_project'),
        ('aAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcalc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calcmachines', to='aAppProject.app_project'),
        ),
        migrations.AlterField(
            model_name='modelcalc_log',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calcmachines_log', to='aAppProject.app_project'),
        ),
    ]
