# Generated by Django 4.2 on 2025-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0008_alter_modelcalc_project_alter_modelcalc_log_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetkey', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('fieldname', models.CharField(max_length=255)),
                ('fieldvalue', models.CharField(max_length=255)),
            ],
        ),
    ]
