# Generated by Django 4.2 on 2025-05-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aAppCalculation', '0009_api_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_keys',
            old_name='type',
            new_name='calctype',
        ),
    ]
