# Generated by Django 4.2 on 2025-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_project',
            name='last_saved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
