# Generated by Django 4.2 on 2025-05-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppProject', '0002_app_project_last_saved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_project',
            name='cover_page_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
