# Generated by Django 4.2 on 2025-06-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aAppProject', '0004_reportprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportprogress',
            name='status',
            field=models.CharField(default='starting', max_length=500),
        ),
    ]
